/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Header: typeof import('./src/components/Header.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    IconBug: typeof import('@arco-design/web-vue/es/icon')['IconBug']
    IconImage: typeof import('@arco-design/web-vue/es/icon')['IconImage']
    IconSave: typeof import('@arco-design/web-vue/es/icon')['IconSave']
    Mode: typeof import('./src/components/Mode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/Side.vue')['default']
    SourceMode: typeof import('./src/components/SourceMode.vue')['default']
    Workspace: typeof import('./src/components/Workspace.vue')['default']
  }
}
